//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVE01_PARTICIPANTE_SERVICIO
    {
        public decimal PARTICIPANTE { get; set; }
        public decimal AREA_SERVICIO { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual EVE01_AREA_SERVICIO EVE01_AREA_SERVICIO { get; set; }
        public virtual EVE01_PARTICIPANTE EVE01_PARTICIPANTE { get; set; }
    }
}
