//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE01.DO.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVE01_EVENTO_OPCION
    {
        public EVE01_EVENTO_OPCION()
        {
            this.EVE01_RECIBO_DETALLE = new HashSet<EVE01_RECIBO_DETALLE>();
        }
    
        public decimal OPCION { get; set; }
        public Nullable<decimal> EVENTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string OBLIGATORIO { get; set; }
        public string ES_TRANSPORTE { get; set; }
        public string ES_HOSPEDAJE { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual ICollection<EVE01_RECIBO_DETALLE> EVE01_RECIBO_DETALLE { get; set; }
        public virtual EVE01_EVENTO EVE01_EVENTO { get; set; }
    }
}
