//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVE01.DO.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesEVE01 : DbContext
    {
        public EntitiesEVE01()
            : base("name=EntitiesEVE01")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EVE01_AREA_SERVICIO> EVE01_AREA_SERVICIO { get; set; }
        public DbSet<EVE01_CORRELATIVO> EVE01_CORRELATIVO { get; set; }
        public DbSet<EVE01_ESTADO> EVE01_ESTADO { get; set; }
        public DbSet<EVE01_EVENTO_ACTUALIZACION> EVE01_EVENTO_ACTUALIZACION { get; set; }
        public DbSet<EVE01_INSCRIPCION> EVE01_INSCRIPCION { get; set; }
        public DbSet<EVE01_INSCRIPCION_OPCION> EVE01_INSCRIPCION_OPCION { get; set; }
        public DbSet<EVE01_PARTICIPANTE> EVE01_PARTICIPANTE { get; set; }
        public DbSet<EVE01_PARTICIPANTE_SERVICIO> EVE01_PARTICIPANTE_SERVICIO { get; set; }
        public DbSet<EVE01_USUARIO> EVE01_USUARIO { get; set; }
        public DbSet<EVE01_EVENTO_OPCION> EVE01_EVENTO_OPCION { get; set; }
        public DbSet<EVE01_PARTICIPANTE_SALDO> EVE01_PARTICIPANTE_SALDO { get; set; }
        public DbSet<EVE01_INSCRIPCION_BUS> EVE01_INSCRIPCION_BUS { get; set; }
        public DbSet<EVE01_MOVIMIENTO> EVE01_MOVIMIENTO { get; set; }
        public DbSet<EVE01_RECIBO_DETALLE> EVE01_RECIBO_DETALLE { get; set; }
        public DbSet<EVE01_TIPO_MOVIMIENTO> EVE01_TIPO_MOVIMIENTO { get; set; }
        public DbSet<EVE01_TIPO_PAGO> EVE01_TIPO_PAGO { get; set; }
        public DbSet<EVE01_EVENTO_BUS> EVE01_EVENTO_BUS { get; set; }
        public DbSet<EVE01_EVENTO> EVE01_EVENTO { get; set; }
        public DbSet<EVE01_EVENTO_SILLA> EVE01_EVENTO_SILLA { get; set; }
        public DbSet<EVE01_INSCRIPCION_SILLA> EVE01_INSCRIPCION_SILLA { get; set; }
        public DbSet<EVE01_RECIBO> EVE01_RECIBO { get; set; }
        public DbSet<EVE01_INSCRIPCION_HOSPEDAJE> EVE01_INSCRIPCION_HOSPEDAJE { get; set; }
        public DbSet<EVE01_SILLA_ANULADA> EVE01_SILLA_ANULADA { get; set; }
    }
}
